"""empty message

Revision ID: 1da0ccb9dbac
Revises: ea75d59df68b
Create Date: 2020-02-11 22:40:24.328061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da0ccb9dbac'
down_revision = 'ea75d59df68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoice', sa.Column('total_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_invoice', 'total_amount')
    # ### end Alembic commands ###
