"""empty message

Revision ID: ea75d59df68b
Revises: f3a4511cd542
Create Date: 2020-02-07 22:36:32.362111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea75d59df68b'
down_revision = 'f3a4511cd542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_invoice', 'contact_name',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    op.alter_column('sales_invoice', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('sales_invoice', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sales_invoice', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('sales_invoice', 'invoice_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_invoice', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales_invoice', 'unit_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_invoice', 'unit_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_invoice', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_invoice', 'invoice_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_invoice', 'invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sales_invoice', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sales_invoice', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('sales_invoice', 'contact_name',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    # ### end Alembic commands ###
